### ISSUE TITLE
Fails to install on OS X

### ISSUE THREAD

**Issue by uranusjr** [Softmotions/ejdb-node#12]
* OS: 10.10.3
* NPM: 2.11.0
* ejdb@1.2.6-3

(C library built and installed successfully. Log skipped.)

~~~
module.js:338
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ejdb
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-gyp process exited with code 1
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "ejdb"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! ejdb@1.2.6-3 install: `node-pre-gyp install --silent || node platform.js preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejdb@1.2.6-3 install script 'node-pre-gyp install --silent || node platform.js preinstall'.
npm ERR! This is most likely a problem with the ejdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --silent || node platform.js preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls ejdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/uranusjr/Downloads/npm-debug.log
~~~

Log file: <http://d.pr/f/13tWT+>

**Comment by uranusjr** [comment]
Installation completes after I install `nan` first. So this is likely a dependency problem?

**Comment by akaustel** [comment]
I can confirm same problem with `ejdb 1.2.8-26` on linux. Should `nan` be added as dependency?

**Comment by akaustel** [comment]
Bump. Still not working in `ejdb@1.2.9-27` on linux.

**Comment by dropfen** [comment]
@uranusjr Thanks for pointing to nan.
There also was an nan major update to the nan api, a lot of calls produced errors when I tried to compile it. To fix it, you should also define the nan version. For me 1.8.x did it

**Comment by akaustel** [comment]
@tyutyunkov this is still an issue in `ejdb@1.2.10-34`. Any plans on fixing this?

**Comment by dropfen** [comment]
@akaustel which *nan* version?

**Comment by akaustel** [comment]
I would like the installation not to require me to install `nan` separately. I.e. if my project is dependent on `ejdb`, I wish to install my project with `npm i -g project-name`, and then run it. Now I am required to first install `nan` and the install my project, or am I missing something?

**Comment by dropfen** [comment]
you need to install NAN to compile ejdb.. I made this PR, because it fixes the NAN version. You can pull my ejdb fork, or just define „nan": "^1.7.0“ in your devDependencies..

**Comment by akaustel** [comment]
Using my fix https://github.com/Softmotions/ejdb-node/pull/14, I am able to install `ejdb` without first installing `nan`. I updated the `nan` version to `^1.9.0`. Feel free to test it using `npm i https://mist.controlthings.fi/ejdb-1.2.10-34.tgz`. Make sure you don't have `nan` globally installed before testing it.

**Comment by dropfen** [comment]
@akaustel 
Your PR is wrong, because you put nan in production dependencies.. It’s enough to have it in devDependencies..
(just for the install/compile step)

**Comment by akaustel** [comment]
I beg to differ. `nan` _is_ a production dependency. Check the `nan` documentation (https://github.com/nodejs/nan): 

```
Simply add NAN as a dependency in the package.json of your Node addon:

$ npm install --save nan
```

Also this way the installation works as you would expect, without manually installing dependencies.

**Comment by dropfen** [comment]
@akaustel 
Hmm, yeah I agree that is right to put nan in dependencies. But your PR is wrong anyway.. Because in this case you don't need nan in devDependencies anymore ;)

**Comment by akaustel** [comment]
I removed `nan` from devDependences and pushed it to the PR https://github.com/Softmotions/ejdb-node/pull/14.

**Comment by akaustel** [comment]
@dropfen are we in agreement of supporting the PR https://github.com/Softmotions/ejdb-node/pull/14? If so we could ask @tyutyunkov to merge it.

**Comment by dropfen** [comment]
@akaustel 
Sure, I agree. Should be merged, otherwise it’s not possible to `npm install ejdb`!

@tyutyunkov, плиз залейте патч парни! (please merge the patch, guys)

**Comment by simplesmiler** [comment]
Looking forward for the #14 to be merged.

**Comment by akaustel** [comment]
@adamansky, we would really like this to be fixed. Pull request #14 fixes the installation problems related to `nan` on all platforms. It would be nice not to be in need of a forked version.

**Comment by ryuken** [comment]
#================================================================
# Ready to install.
#================================================================
  CXX(target) Release/obj.target/ejdb_native/ejdb_native.o
In file included from ../ejdb_native.cc:23:
../ejdb_cmd.h:75:61: error: too few arguments to function call, expected 2, have 1
            this->cb = v8::Persistent<v8::Function>::New(_cb);
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../ejdb_native.cc:89:21: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../ejdb_native.cc:105:21: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../ejdb_native.cc:119:21: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../ejdb_native.cc:133:21: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../ejdb_native.cc:180:21: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../ejdb_native.cc:188:30: error: no member named 'Close' in 'v8::HandleScope'
                return scope.Close(String::New(xoid, 24));
                       ~~~~~ ^
../ejdb_native.cc:188:44: error: no member named 'New' in 'v8::String'
                return scope.Close(String::New(xoid, 24));
                                   ~~~~~~~~^
../ejdb_native.cc:192:30: error: no member named 'Close' in 'v8::HandleScope'
                return scope.Close(String::New(bson_iterator_string(it), bson_iterator_string_len(it) - 1));
                       ~~~~~ ^
../ejdb_native.cc:192:44: error: no member named 'New' in 'v8::String'
                return scope.Close(String::New(bson_iterator_string(it), bson_iterator_string_len(it) - 1));
                                   ~~~~~~~~^
../ejdb_native.cc:194:30: error: no member named 'Close' in 'v8::HandleScope'
                return scope.Close(Null());
                       ~~~~~ ^
../ejdb_native.cc:194:36: error: no matching function for call to 'Null'
                return scope.Close(Null());
                                   ^~~~
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:306:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Null(Isolate* isolate);
                           ^
../ejdb_native.cc:196:30: error: no member named 'Close' in 'v8::HandleScope'
                return scope.Close(Undefined());
                       ~~~~~ ^
../ejdb_native.cc:196:36: error: no matching function for call to 'Undefined'
                return scope.Close(Undefined());
                                   ^~~~~~~~~
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../ejdb_native.cc:198:30: error: no member named 'Close' in 'v8::HandleScope'
                return scope.Close(Integer::New(bson_iterator_int_raw(it)));
                       ~~~~~ ^
../ejdb_native.cc:198:74: error: too few arguments to function call, expected 2, have 1
                return scope.Close(Integer::New(bson_iterator_int_raw(it)));
                                   ~~~~~~~~~~~~                          ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:2012:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../ejdb_native.cc:200:30: error: no member named 'Close' in 'v8::HandleScope'
                return scope.Close(Number::New((double) bson_iterator_long_raw(it)));
                       ~~~~~ ^
../ejdb_native.cc:200:83: error: too few arguments to function call, expected 2, have 1
                return scope.Close(Number::New((double) bson_iterator_long_raw(it)));
                                   ~~~~~~~~~~~                                    ^
/Users/taushif/.node-gyp/0.12.7/deps/v8/include/v8.h:1999:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../ejdb_native.cc:202:30: error: no member named 'Close' in 'v8::HandleScope'
                return scope.Close(Number::New(bson_iterator_double_raw(it)));
                       ~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by akaustel** [comment]
@ryuken could you please tell us what this is?

**Comment by ryuken** [comment]
Sorry it's after you use npm install ejdb

**Comment by akaustel** [comment]
It does not seem you read through the thread. There is a suggested fix, did you try it? For your convenience you can try it as described earlier using: `npm install https://mist.controlthings.fi/ejdb-1.2.10-34.tgz`. You will need build tools like `cmake` to get it done. In case the fix does not work for you then we would gladly try to help you out. In case it works, please just agree to merge the fix as others have done.

**Comment by thejustinwalsh** [comment]
@akaustel Using the URL you have posted with node 4.1.1 on El Capitan it still fails when compiling the native interface. Do i need a different version of node.js to get it working? I tried nave and when i did nam it still detected the most recent version of node.js installed.

**Comment by akaustel** [comment]
@thejustinwalsh I have only tested it on El Capitan with node 0.10.40. It would seem that the EJDB team does not have time to maintain this package. Can you say why it failed? Do you have xcode and cmake installed? I don't have a lot of time myself, but I'll try to see if I can reproduce you problem.

**Comment by MrApe** [comment]
Using the url above gives me a bunch of compile errors:

e.g.:
```
In file included from ../ejdb_native.cc:17:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
```

I'm on OS X 10.11.4 using node 5.10.1.
