### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by skn2020** [Softmotions/ejdb-node#15]
Hi,  I tried to install the CLI (node module) for EJDB (on CentOS 7, node version v0.10.36, npm version 1.3.6) using both of these commands (getting the same result):
```
npm install -g ejdb
npm install --build-from-source -g ejdb
```
After several lines of successful build, I am getting the following error:
```
npm http GET https://registry.npmjs.org/ejdb
npm http 304 https://registry.npmjs.org/ejdb
............
............
............
make[1]: Leaving directory `/usr/lib/node_modules/ejdb/build-ejdb'

module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-123.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ejdb
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
node-gyp process exited with code 1
npm ERR! weird error 1
npm ERR! not ok code 0
```

Please help. Thanks.

**Comment by akaustel** [comment]
I believe we have fixed the problem in issue #12, but are waiting for someone (@adamansky or @tyutyunkov)  with commit access to merge the fix. See: https://github.com/Softmotions/ejdb-node/pull/14. You may test the fix yourself using `npm i https://mist.controlthings.fi/ejdb-1.2.10-34.tgz`.

**Comment by skn2020** [comment]
@akaustel your package worked. Thanks. I think my problem was nan version being 2.0.8.
