### ISSUE TITLE
npm install fails for ubuntu

### ISSUE THREAD

**Issue by revaries** [Softmotions/ejdb-node#16]
Attaching the log for reference

[npm-debug.txt](https://github.com/Softmotions/ejdb-node/files/202150/npm-debug.txt)

**Comment by akaustel** [comment]
Hi @revaries! There is a known issue in the package, for which there is a fix that has not yet been merged. To test if you have the same issue, try to install `nan@1.9` and then install `ejdb`. There is a pull request #14, which fixes that problem. If this was your problem, please endorse the pull request with a comment.

**Comment by wgerven** [comment]
I'm on xubuntu 14.04, and had the same problem with `nan` package. However, after adding `nan`, I still cannot successfully install ejdb. 
[npm-debug.txt](https://github.com/Softmotions/ejdb-node/files/491139/npm-debug.txt)

**Comment by akaustel** [comment]
Did you, @wgerven, install the specified version of `nan@1.9`?

**Comment by wgerven** [comment]
Hi @akaustel, thanks for the pointer. Before I didn't have, so that was stupid of me. Now I have, but it only solved part of the problem. I think the following is the relevant part of the terminal output, before that all appeared to be built fine.
```
...
[100%] Built target jbfmgr
make[2]: Leaving directory `/home/user/test/node_modules/ejdb/build-ejdb'
Install the project...
-- Install configuration: "Release"
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/lib/pkgconfig/libejdb.pc
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/lib/libejdb.so.1.2.10
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/lib/libejdb.so.1
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/lib/libejdb.so
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/tcutil.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/tchdb.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/tcbdb.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/tctdb.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/tcfdb.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/bson.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/ejdb.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/basedefs.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/include/ejdb/ejdb_private.h
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/share/ejdb/ejdb-exports.cmake
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/share/ejdb/ejdb-exports-release.cmake
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/lib/libejdb-1.a
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/share/doc/ejdb/LICENSE
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/share/doc/ejdb/INSTALL
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/share/doc/ejdb/Changelog
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/share/doc/ejdb/README
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/bin/jbhmgr
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/bin/jbbmgr
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/bin/jbtmgr
-- Installing: /home/user/test/node_modules/ejdb/build-ejdb/libejdb/bin/jbfmgr
make[1]: Leaving directory `/home/user/test/node_modules/ejdb/build-ejdb'
make: Entering directory `/home/user/test/node_modules/ejdb/build'
  CXX(target) Release/obj.target/ejdb_native/ejdb_native.o
In file included from ../ejdb_native.cc:17:0:
../../nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../../nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../../nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h:768:67: note: candidates are:
In file included from ../../nan/nan.h:25:0,
                 from ../ejdb_native.cc:17:
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:31:40: note:   candidate expects 2 arguments, 3 provided
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:34:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:34:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:39:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 3 provided
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:46:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/wgerven/.node-gyp/4.5.0/include/node/node_buffer.h:46:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../ejdb_native.cc:17:0:
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../ejdb_native.cc: In member function ‘void ejdb::NodeEJDB::sync_after(ejdb::NodeEJDB::EJBTask*)’:
../ejdb_native.cc:1140:41: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                 FatalException(try_catch);
                                         ^
../ejdb_native.cc: In member function ‘void ejdb::NodeEJDB::set_index_after(ejdb::NodeEJDB::SetIndexCmdTask*)’:
../ejdb_native.cc:1177:41: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                 FatalException(try_catch);
                                         ^
../ejdb_native.cc: In member function ‘void ejdb::NodeEJDB::rm_collection_after(ejdb::NodeEJDB::RMCollCmdTask*)’:
../ejdb_native.cc:1204:41: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                 FatalException(try_catch);
                                         ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::remove_after(ejdb::NodeEJDB::BSONCmdTask*)’:
../ejdb_native.cc:1244:45: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                     FatalException(try_catch);
                                             ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::txctl_after(ejdb::NodeEJDB::TxCmdTask*)’:
../ejdb_native.cc:1315:45: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                     FatalException(try_catch);
                                             ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::save_after(ejdb::NodeEJDB::BSONCmdTask*)’:
../ejdb_native.cc:1384:45: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                     FatalException(try_catch);
                                             ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::load_after(ejdb::NodeEJDB::BSONCmdTask*)’:
../ejdb_native.cc:1433:45: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                     FatalException(try_catch);
                                             ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::open_after(ejdb::NodeEJDB::OpenCmdTask*)’:
../ejdb_native.cc:1568:41: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                 FatalException(try_catch);
                                         ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::close_after(ejdb::NodeEJDB::EJBTask*)’:
../ejdb_native.cc:1608:41: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                 FatalException(try_catch);
                                         ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::ensure_after(ejdb::NodeEJDB::EnsureCmdTask*)’:
../ejdb_native.cc:1646:41: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                 FatalException(try_catch);
                                         ^
../ejdb_native.cc: In member function ‘v8::Handle<v8::Value> ejdb::NodeEJDB::query_after(ejdb::NodeEJDB::BSONQCmdTask*)’:
../ejdb_native.cc:1992:45: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                     FatalException(try_catch);
                                             ^
../ejdb_native.cc:2024:41: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/wgerven/.node-gyp/4.5.0/include/node/node.h:283): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
                 FatalException(try_catch);
                                         ^
In file included from ../ejdb_native.cc:17:0:
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:769:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make: *** [Release/obj.target/ejdb_native/ejdb_native.o] Error 1
make: Leaving directory `/home/user/test/node_modules/ejdb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-96-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/test/node_modules/ejdb
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-gyp process exited with code 1
npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "ejdb" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! ejdb@1.2.10-34 install: `node-pre-gyp install --silent || node platform.js preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejdb@1.2.10-34 install script 'node-pre-gyp install --silent || node platform.js preinstall'.
npm ERR! This is most likely a problem with the ejdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --silent || node platform.js preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ejdb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ejdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/test/npm-debug.log
```

**Comment by akaustel** [comment]
My current node setup is 0.10.31, and I'm busy at the moment, but I'll get back to you as soon as I get back to work early next week :-). In the mean time you could try out some older version if you're in a hurry.

**Comment by wgerven** [comment]
Hi @akaustel, not in a hurry :) But thanks a lot for paying attention to my issue.

**Comment by akaustel** [comment]
It would seen that `node 4.5` is not compatible with the lastest version of `nan` which `ejdb` supports . I tried out some `nan` versions but I could not find a configuration that work with that `node` version. The version of `nan` which I know is working is `1.9.0`, which states support for `node 0.8`, `0.10` and `0.12` as well as `io.js`. Unfortunately I don't have time to fix the issue right now, but If you can work with an older `node` for the time being, I'm sure this will be sorted out in due time.

**Comment by heliar** [comment]
Hi all, should be fixed by now.
